export const ORDER_STATUS=[{name:'待面试',id:5,color:'#E9AC7E'},{name:'面试结束',id:10,color:'#CECFD1'},{name:'待签约',id:20,color:'#7DB5FB'},{name:'取消合作',id:40,color:'#CECFD1'},{name:'取消预约',id:35,color:'#CECFD1'},{name:'合同期满',id:30,color:''},{name:'签约成功',id:25,color:''},{name:'上门试工',id:15,color:''}]; //订单状态
export const ORDER_DETAIL_STATUS=[{name:'取消面试',id:5,color:'#E9AC7E'},{name:'面试结束',id:10,color:'#CECFD1'},{name:'待签约',id:20,color:'#7DB5FB'},{name:'取消合作',id:40,color:'#CECFD1'},{name:'取消预约',id:35,color:'#CECFD1'},{name:'合同期满',id:30,color:''},{name:'签约成功',id:25,color:''},{name:'上门试工',id:15,color:''}];
export const INTERVIEW_TYPE=[{name:'到店面试',id:1},{name:'上门面试',id:2},{name:'视频面试',id:3}];
export const WORK_TYPE=[{name:'月嫂',id:1},{name:'保姆',id:2},{name:'育儿嫂',id:3}];
export const IDENTITY_TYPE=[{name:'准妈妈',id:1},{name:'备孕宝妈',id:2},{name:'宝妈',id:3},{name:'家属',id:4},{name:'神秘人',id:5}];
export const SERVICE_PERIOD_STATUS=[{name:'标准周期12个月',id:1},{name:'灵活周期6个月',id:2},{name:'随心周期3个月',id:3}];
export const SERVICE_TYPE=[{name:'住家',id:1},{name:'白班',id:2}];
export const WORK_STATUS=[{name:'在职',id:1},{name:'离职',id:2},{name:'正在找工作',id:3}];
export const SELECT_SERVICE_TYPE=[{name:'月嫂',id:1},{name:'保姆',id:2},{name:'育儿嫂',id:3},{name:'小时工',id:4},{name:'催乳师',id:5},{name:'先逛逛',id:6}];
